name: deploy_frontend

on:
  # Allow to run the workflow manually from Actions tab
  workflow_dispatch:
    inputs:
      baseversion:
        description: 'Image base version'
        required: true
        default: '0.2'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: sebastart/nodigium-frontend
      DOCKER_TARGET_PLATFORM: linux/arm64,linux/arm/v7,linux/arm/v6
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::$DOCKER_TARGET_PLATFORM
          echo ::set-output name=docker_image::$DOCKER_IMAGE
          echo ::set-output name=version::${{ github.event.inputs.baseversion }}.$GITHUB_RUN_NUMBER
      -
        name: Log into registry docker hub
        if: |
          success() && 
          github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build docker image
        if: success()
        working-directory: src
        run: |
          docker buildx build . \
            --platform ${{ steps.prepare.outputs.docker_platform }} \
            --file ../deployment/frontend.Dockerfile \
            --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
            --tag ${{ steps.prepare.outputs.docker_image }}:latest \
            --output type=image,push=true
  deploy:
    env:
      DOCKER_IMAGE: sebastart/nodigium-frontend
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_DOMAIN }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml